name: demo-aws-client
on:
  push:
    branches:
      - 'main'
    paths:
      - 'demo/aws/demo-aws-client/**'
jobs:
  build-publish-aws:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@perfect-stack'
      - name: npm ci
        working-directory: ./demo/aws/demo-aws-client
        run: npm ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: npm run build
        working-directory: ./demo/aws/demo-aws-client
        run: npm run build
#      - name: bump version
#        working-directory: ./demo/aws/demo-aws-client
#        run: npm version patch
#      - name: commit push
#        uses: EndBug/add-and-commit@v9
#        with:
#          default_author: github_actions
#          tag: ${{ env.TAG_NAME }}
#      - name: setup npmrc for docker build
#        working-directory: ./demo/aws/demo-aws-client
#        run: |
#          echo "@perfect-stack:registry=https://npm.pkg.github.com" >> .npmrc
#          echo "//npm.pkg.github.com/:_authToken=\${NPM_TOKEN}" >> .npmrc
#          cat .npmrc
      - name: debug
        working-directory: ./demo/aws/demo-aws-client
        run: ls -al
