name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-hello-github-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello World!"
      - uses: actions/checkout@v2
      - name: Run CDK
        run: |
          cd demo/cdk/hello-github &&
          ls &&
          cdk deploy --require-approval never HelloGithubStack
        
