name: Hello World
on: [push]

jobs:
  Hello-World-Job:
    # This dynamic runner label suggests a custom self-hosted runner setup.
    # The steps below assume this runner might be a minimal environment
    # where Node.js and AWS CDK CLI need to be installed.
    # If this runner is *intended* to have these tools pre-installed,
    # then the runner's configuration/image should be updated externally.
    runs-on:
      - codebuild-hello-github-${{ github.run_id }}-${{ github.run_attempt }}
    # For testing or if you prefer a standard environment, you could use:
    # runs-on: ubuntu-latest

    steps:
      - run: echo "Hello World!"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install AWS CDK CLI
        run: npm install -g aws-cdk

      # Configure AWS credentials before running 'cdk deploy'.
      # This step is crucial for CDK to interact with your AWS account.
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # OPTION 1: OpenID Connect (OIDC) - Recommended for security
          # Prerequisites:
          # 1. IAM OIDC provider in AWS for GitHub Actions.
          # 2. An IAM role with trust policy for the OIDC provider and necessary permissions for CDK.
          ##role-to-assume: arn:aws:iam::YOUR_AWS_ACCOUNT_ID:role/YOUR_GITHUB_ACTIONS_CDK_ROLE # Replace with your Role ARN
          role-to-assume: arn:aws:iam::100150877581:role/service-role/codebuild-hello-github-service-role
          aws-region: ap-southeast-2

          # OPTION 2: AWS Access Keys (Less secure - use GitHub secrets)
          # Ensure you have AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY configured as secrets in your GitHub repository.
          # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # aws-region: YOUR_AWS_REGION # e.g., us-east-1. Replace with your deployment region.

      - name: Run CDK Commands
        working-directory: ./demo/cdk/hello-github
        run: |
          # Install project-specific dependencies (e.g., aws-cdk-lib, constructs)
          # defined in your package.json
          npm install
          
          # Bootstrap your AWS environment for CDK, if not already done.
          # This provisions necessary resources like an S3 bucket for assets.
          # It uses the AWS credentials and region configured in the previous step.
          # You might need to run this once per account/region, or ensure your
          # CI/CD role has permissions to manage the CDKToolkit stack.
          cdk bootstrap
          
          # If you need to specify account/region explicitly (e.g. for cross-account):
          # cdk bootstrap aws://YOUR_AWS_ACCOUNT_ID/YOUR_AWS_REGION

          # Deploy your CDK stack
          cdk deploy HelloGithubStack --require-approval never