name: nestjs-server
# Concurrency is limited to the main branch because of how two builds can't update their own version numbers at the same time
concurrency: single_main_branch_build
on:
  push:
    branches:
      - 'main'
    paths:
      - 'nestjs-server/**'
jobs:
  publish-github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@perfect-stack'
      - name: npm ci
        working-directory: ./nestjs-server
        run: npm ci
      - name: npm run build
        working-directory: ./nestjs-server
        run: npm run build
      - name: debug
        working-directory: ./nestjs-server
        run: ls -al
      - name: bump version
        working-directory: ./nestjs-server
        run: npm version patch
      - name: get version
        working-directory: ./nestjs-server
        run: |
          export NPM_PKG_VERSION=$(npm pkg get version | sed 's/"//g')
          echo "TAG_NAME=nestjs-server-$NPM_PKG_VERSION" >> $GITHUB_ENV
      - name: commit push
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          tag: ${{ env.TAG_NAME }}
      - name: release
        working-directory: ./nestjs-server
        run: npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
