name: nestjs-server-actions
on:
  push:
    paths:
      - 'nestjs-server/**'
jobs:
  publish-github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@perfect-stack'
      - name: npm ci
        working-directory: ./nestjs-server
        run: npm ci
      - name: npm run build
        working-directory: ./nestjs-server
        run: npm run build
      - name: npm publish
        working-directory: ./nestjs-server
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}