name: nestjs-server-actions
on:
  push:
    paths:
      - 'nestjs-server/**'
jobs:
  publish-github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: npm install
        working-directory: ./nestjs-server
        run: npm install
      - name: ls
        working-directory: ./nestjs-server
        run: ls -al
      - name: npm run build
        working-directory: ./nestjs-server
        run: npm run build
