name: ngx-perfect-stack-actions
on:
  push:
    branches:
      - 'main'
    paths:
      - 'angular-workspace/**'
jobs:
  publish-github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@perfect-stack'
      - name: npm ci
        working-directory: ./angular-workspace
        run: npm ci
      - name: npm run build
        working-directory: ./angular-workspace
        run: npm run build
#      - name: release
#        working-directory: ./angular-workspace
#        run: npx semantic-release
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
